import type { NextPage } from "next";
import Head from "next/head";
import { useForm } from "react-hook-form";
import axios from "axios";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  const { register, handleSubmit } = useForm();
  const onSubmit = async (data: any) => {
    console.log(data);
    const response = await axios.post("/api/register");
    console.log(response);
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <form onSubmit={handleSubmit(onSubmit)}>
            <input type="text" {...register("name")} />
            <input type="email" {...register("email")} />
            <input type="password" {...register("password")} />
            <button type="submit">Send</button>
          </form>
        </main>
      </div>
    </div>
  );
};

export default Home;
